site_name: Data Science Workflow Management
site_description: 'Data Science Workflow Management'
site_author: Ibon Martínez-Arranz
site_url: https://github.com/imarranz/data-science-workflow-management
repo_url: https://github.com/imarranz/data-science-workflow-management

docs_dir: srcsite
site_dir: website

use_directory_urls: false

theme:
  name: readthedocs #mkdocs # https://mkdocs.readthedocs.io/en/0.13.3/user-guide/styling-your-docs/l
  #custom_dir: mkdocs-bootstrap4-master/mkdocs_bootstrap4
  color_mode: auto
  #user_color_mode_toggle: true
  palette:
    primary: 'yellow'
    accent: 'deep orange'
  social:
    - type: github-alt
      link: https://github.com/imarranz
    - type: twitter
      link: https://twitter.com/imarranz
    - type: linkedin
      link: https://www.linkedin.com/in/ibon-martinez-arranz/
  nav_style: dark #primary #dark
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
  include_sidebar: true
  include_homepage_in_sidebar: true
  prev_next_buttons_location: top #bottom # bottom, top, both, none.
  titles_only: true
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

# conda install -c conda-forge pymdown-extensions
# https://squidfunk.github.io/mkdocs-material/extensions/pymdown/

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 1
      toc_depth: 6
      separator: "_"
  - footnotes
  - fenced_code

plugins:
  - search

extra:
  version: 1.0

extra_css:
  - 'css/custom.css'

extra_javascript:
#  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - 'Data Science Workflow Management': index.md
  - 'Introduction':
    - 'Introduction': 01_introduction/011_introduction.md
    - 'What is Data Science Workflow Management?': 01_introduction/012_introduction.md
    - 'References': 01_introduction/013_introduction.md
  - 'Fundamentals of Data Science':
    - 'Fundamentals of Data Science': 02_fundamentals/021_fundamentals_of_data_science.md
    - 'What is Data Science?': 02_fundamentals/022_fundamentals_of_data_science.md
    - 'Data Science Process': 02_fundamentals/023_fundamentals_of_data_science.md
    - 'Programming Languages for Data Science': 02_fundamentals/024_fundamentals_of_data_science.md
    - 'Data Science Tools and Technologies': 02_fundamentals/025_fundamentals_of_data_science.md
    - 'References': 02_fundamentals/026_fundamentals_of_data_science.md
  - 'Workflow Management Concepts':
    - 'Workflow Management Concepts': 03_workflow/031_workflow_management_concepts.md
    - 'What is Workflow Management?': 03_workflow/032_workflow_management_concepts.md
    - 'Why is Workflow Management Important?': 03_workflow/033_workflow_management_concepts.md
    - 'Workflow Management Models': 03_workflow/034_workflow_management_concepts.md
    - 'Workflow Management Tools and Technologies': 03_workflow/035_workflow_management_concepts.md
    - 'Enhancing Collaboration and Reproducibility through Project Documentation': 03_workflow/036_workflow_management_concepts.md
    - 'Practical Example': 03_workflow/037_workflow_management_concepts.md
    - 'References': 03_workflow/038_workflow_management_concepts.md
  - 'Project Planning':
    - 'Project Planning': 04_project/041_project_plannig.md
    - 'What is Project Planning?': 04_project/042_project_plannig.md
    - 'Problem Definition and Objectives': 04_project/043_project_plannig.md
    - 'Selection of Modelling Techniques': 04_project/044_project_plannig.md
    - 'Selection Tools and Technologies': 04_project/045_project_plannig.md
    - 'Workflow Design': 04_project/046_project_plannig.md
    - 'Practical Example': 04_project/047_project_plannig.md
  - 'Data Acquisition':
    - 'Data Acquisition and Preparation': 05_acquisition/0510_data_acquisition_and_preparation.md
    - 'What is Data Acquisition?': 05_acquisition/0520_data_acquisition_and_preparation.md
    - 'Selection of Data Sources': 05_acquisition/0530_data_acquisition_and_preparation.md
    - 'Data Extraction and Transformation': 05_acquisition/0541_data_acquisition_and_preparation.md
    - 'Data Profiling': 05_acquisition/0542_data_acquisition_and_preparation.md
    - 'Data Cleaning': 05_acquisition/0550_data_acquisition_and_preparation.md
    - 'Data Integration': 05_acquisition/0560_data_acquisition_and_preparation.md
    - 'Practical Example': 05_acquisition/0570_data_acquisition_and_preparation.md
    - 'References': 05_acquisition/0580_data_acquisition_and_preparation.md
  - 'Exploratory Data Analysis':
    - 'Exploratory Data Analysis': 06_eda/061_exploratory_data_analysis.md
    - 'Descriptive Statistics': 06_eda/062_exploratory_data_analysis.md
    - 'Data Visualization': 06_eda/063_exploratory_data_analysis.md
    - 'Correlation Analysis': 06_eda/064_exploratory_data_analysis.md
    - 'Data Transformation': 06_eda/065_exploratory_data_analysis.md
    - 'Practical Example': 06_eda/066_exploratory_data_analysis.md
    - 'References': 06_eda/067_exploratory_data_analysis.md
  - 'Modelling and Data Validation':
    - 'Modelling and Data Validation': 07_modelling/071_modeling_and_data_validation.md
    - 'What is Data Modelling': 07_modelling/072_modeling_and_data_validation.md
    - 'Selection of Modelling Algortihms': 07_modelling/073_modeling_and_data_validation.md
    - 'Model Training and Validation': 07_modelling/074_modeling_and_data_validation.md
    - 'selection of Best Model': 07_modelling/075_modeling_and_data_validation.md
    - 'Model Evaluation': 07_modelling/076_modeling_and_data_validation.md
    - 'Model Interpretability': 07_modelling/077_modeling_and_data_validation.md
    - 'Practical Example': 07_modelling/078_modeling_and_data_validation.md
    - 'References': 07_modelling/079_modeling_and_data_validation.md
  - 'Model Implementation':
    - 'Model Implementation and Maintenance': 08_implementation/081_model_implementation_and_maintenance.md
    - 'What is Model Implementation?': 08_implementation/082_model_implementation_and_maintenance.md
    - 'selection of Implementation Platform': 08_implementation/083_model_implementation_and_maintenance.md
    - 'Integration with Existing Systems': 08_implementation/084_model_implementation_and_maintenance.md
    - 'Testing and Validation of the Model': 08_implementation/085_model_implementation_and_maintenance.md
    - 'Model Maintenance and Updating': 08_implementation/086_model_implementation_and_maintenance.md
  - 'Monitoring and Improvement':
    - 'Monitoring and Improvement': 09_monitoring/091_monitoring_and_continuos_improvement.md
    - 'What is Monitoring and Continuous Improvement?': 09_monitoring/092_monitoring_and_continuos_improvement.md
    - 'Model Performance Monitoring': 09_monitoring/093_monitoring_and_continuos_improvement.md
    - 'Problem Identification': 09_monitoring/094_monitoring_and_continuos_improvement.md
    - 'Continuous Model Improvement': 09_monitoring/095_monitoring_and_continuos_improvement.md
    - 'References': 09_monitoring/096_monitoring_and_continuos_improvement.md


copyright: '<b>Data Science Workflow Management</b><br>Copyright &#169; 2024 <a href="https://github.com/imarranz">Ibon Martínez-Arranz</a><br>'


#copyright: '<b>Essential Guide to Pandas<br>
#<i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i> &emsp;
#<i class="fa fa-envelope fa-2x" aria-hidden="true"></i>  &emsp;
#<i class="fa fa-youtube-play fa-2x" aria-hidden="true"></i>  &emsp;
#<a href="https://github.com/imarranz/essential-guide-to-pandas" target="_blank" title="Essential Guide to Pandas"><i class="fa fa-firefox fa-2x" aria-hidden="true"></i></a>
#<br>Copyright &#169; 2024<br>'
